docs: Move repository-settings and add info on additional workflows needed
asyncapi/.github pull request #11
Opened 2020-10-17 09:00 UTC by ab510

**Description**

Moved repository settings file from https://github.com/asyncapi/asyncapi/blob/master/documents/repository-settings.md and added additional info file as specified by issue.

**Related issue(s)**
See also #7

2020-10-18 16:31 UTC, derberg requested changes
Great stuff! I added 2 comments about stuff that were not mentioned in the issues, sorry but they changed during hacktoberfest

2020-10-18 16:31 UTC, derberg commented on repository-settings.md
> +      pull_request:
```suggestion
      pull_request_target:
```

sorry for not pointing it out in the issue. We are now changing to this event in all repositories

2020-10-18 16:31 UTC, derberg commented on repository-settings.md
> +* Release workflow that should be based on the following content:
Could you please add a sentence or something that would indicate/explain that very important is the Twitter part here in this workflow. It was not in the issue as that was added during Hacktoberfest by another contributor -> @juergenbr 

Background: After listening to the voice of the community we decided to tweet only major and minor releases, to not spam community to much with additional information about bug fixes.

It is important to mention here that we should respect that decision and make sure this `if: steps.check.outputs.changed == 'true' && steps.check.outputs.type != 'patch'` validation is always in place to not tweet on `patch` releases

2020-10-18 16:50 UTC, ab510 commented on repository-settings.md
> +* Release workflow that should be based on the following content:
Thank you, I have made the requested changed

2020-10-19 09:16 UTC, derberg commented on repository-settings.md
> +* Of particular note within this workflow is the twitter section. All repositories should ensure that the ``if: steps.check.outputs.changed == 'true' && steps.check.outputs.type != 'patch'`` validati
problem with making it a bullet point is that it looks like this when it is rendered

<img width="1019" alt="Screenshot 2020-10-19 at 11 13 18" src="https://user-images.githubusercontent.com/6995927/96425382-414e1880-11fc-11eb-8b62-ac4488ac5d4f.png">

better, I think, would be to make it just another sentence...or maybe as a comment in the workflow itself? right before the Twitter step with `#` char?

2020-10-19 10:04 UTC, ab510 commented on repository-settings.md
> +* Of particular note within this workflow is the twitter section. All repositories should ensure that the ``if: steps.check.outputs.changed == 'true' && steps.check.outputs.type != 'patch'`` validati
Made the changes.

2020-10-19 10:11 UTC, derberg approved these changes
LGTM!

Thanks so much! Would you mind sharing with me how did you find out about AsyncAPI and this issue? what resources that we prepared did you use? we made some effort into Hacktoberfest and want to identify what efforts were the best for contributors and how they learned about us, so next Hacktoberfest is even better

2020-10-19 10:12 UTC, merged

2020-10-19 10:13 UTC, ab510 commented
> LGTM!
> 
> Thanks so much! Would you mind sharing with me how did you find out about AsyncAPI and this issue? what resources that we prepared did you use? we made some effort into Hacktoberfest and want to identify what efforts were the best for contributors and how they learned about us, so next Hacktoberfest is even better

I found out about it through your discord post on the official Hacktoberfest server. I found the linked webpage useful in getting setup.