ci: include all semantic-release default branches for the release workflow
asyncapi/.github pull request #121
Opened 2022-01-12 21:34 UTC by smoya

**Description**

This PR adds all the default semantic-release branches to the release workflow for node apps.

**Related issue(s)**
Relates to https://github.com/asyncapi/parser-js/pull/442#discussion_r783098429

2022-01-12 21:35 UTC, smoya commented on .github/workflows/if-nodejs-release.yml
> +      - '**-release' # custom
I didn't find this one on the semantic-release docs.

2022-01-12 21:36 UTC, smoya commented on .github/workflows/if-nodejs-release.yml
> -      - '**-release'
The docs also show `'+([0-9])?(.{+([0-9]),x}).x` as regex for the branch name.I think we should also add it but waiting for feedback.

See https://semantic-release.gitbook.io/semantic-release/usage/configuration#branches

2022-01-13 16:06 UTC, derberg commented on .github/workflows/if-nodejs-release.yml
> +      - '**-release' # custom
this one is custom, driven by the discussion we had around release cycle and branch naming for specification where the branch name contains the release month.

2022-01-13 16:06 UTC, derberg commented on .github/workflows/if-nodejs-release.yml
> -      - '**-release'
did you check if GH Actions support such regex, I don't think so afaik

2022-01-18 00:06 UTC, smoya commented on .github/workflows/if-nodejs-release.yml
> -      - '**-release'
No it doesn't. It allows basic filtering but can't formulate something close to that regex. I would just skip this regex for now.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

2022-01-19 11:05 UTC, smoya commented
> lgtm,
> 
> please make additional bug fix not related to your change but just doesn't make sense to overload CI with tiny fixes, so we can add it here:
> 
> * https://github.com/asyncapi/.github/blob/master/.github/workflows/help-command.yml#L13 change from `github.event.issue.pull_request && contains(github.event.comment.body, '/help' && github.actor != 'asyncapi-bot') ` to `github.event.issue.pull_request && contains(github.event.comment.body, '/help') && github.actor != 'asyncapi-bot' `
> * https://github.com/asyncapi/.github/blob/master/.github/workflows/help-command.yml#L29 change from `${{ !github.event.issue.pull_request && contains(github.event.comment.body, '/help') && github.actor != 'asyncapi-bot'}}` to `!github.event.issue.pull_request && contains(github.event.comment.body, '/help') && github.actor != 'asyncapi-bot'`
> 
> 🙏🏼

Ok, time to sound picky here 😅 :
I don't think we should add unexpected changes to this PR. The reason is that the merged commit name will provide insights about what it is doing, and in case something goes wrong when merging, spotting the bug will become harder as some side effects where added. People won't know what really the changes were by reading the commit title and this is, IMHO, a bad practice.
I think we also want other people to don't mix changes on the same PR unless they are 100% related and described.

Therefore, I created a new PR for those changes you suggested here: https://github.com/asyncapi/.github/pull/124

2022-01-19 11:25 UTC, smoya commented
> > lgtm,
> > please make additional bug fix not related to your change but just doesn't make sense to overload CI with tiny fixes, so we can add it here:
> > 
> > * https://github.com/asyncapi/.github/blob/master/.github/workflows/help-command.yml#L13 change from `github.event.issue.pull_request && contains(github.event.comment.body, '/help' && github.actor != 'asyncapi-bot') ` to `github.event.issue.pull_request && contains(github.event.comment.body, '/help') && github.actor != 'asyncapi-bot' `
> > * https://github.com/asyncapi/.github/blob/master/.github/workflows/help-command.yml#L29 change from `${{ !github.event.issue.pull_request && contains(github.event.comment.body, '/help') && github.actor != 'asyncapi-bot'}}` to `!github.event.issue.pull_request && contains(github.event.comment.body, '/help') && github.actor != 'asyncapi-bot'`
> > 
> > 🙏🏼
> 
> Ok, time to sound picky here 😅 : I don't think we should add unexpected changes to this PR. The reason is that the merged commit name will provide insights about what it is doing, and in case something goes wrong when merging, spotting the bug will become harder as some side effects where added. People won't know what really the changes were by reading the commit title and this is, IMHO, a bad practice. I think we also want other people to don't mix changes on the same PR unless they are 100% related and described.
> 
> Therefore, I created a new PR for those changes you suggested here: #124

As @derberg requested, I added the changes in this PR.

2022-01-19 11:28 UTC, derberg commented
I also do not like mixing, just here is exception, not code but ci. We stop doing it once we get https://github.com/asyncapi/.github/issues/116 solved, so basically have solution to skip ci entirely in such PRs

2022-01-19 11:31 UTC, derberg reviewed
LGTM 🚀 

@KhudaDad414 anything from your side?

2022-01-19 11:41 UTC, KhudaDad414 requested changes
LGTM.

2022-01-19 11:41 UTC, KhudaDad414 commented on .github/workflows/help-command.yml
> -    if: ${{ !github.event.issue.pull_request && contains(github.event.comment.body, '/help') && github.actor != 'asyncapi-bot'}}
@derberg are you sure about this one? It gives syntax error without the brackets, at least in my fork. https://github.com/KhudaDad414/.github/actions/runs/1717756142

2022-01-19 11:46 UTC, smoya commented on .github/workflows/help-command.yml
> -    if: ${{ !github.event.issue.pull_request && contains(github.event.comment.body, '/help') && github.actor != 'asyncapi-bot'}}
Yes, it does. Missing tag. I thought this was handled by github when running the workflow. Thoughts @derberg?

2022-01-19 11:49 UTC, derberg commented on .github/workflows/help-command.yml
> -    if: ${{ !github.event.issue.pull_request && contains(github.event.comment.body, '/help') && github.actor != 'asyncapi-bot'}}
I'm pretty sure I read in docs it is fine, but have nothing against adding them, just to be save, but then add it to all ifs in this workflow please

2022-01-19 12:36 UTC, smoya commented on .github/workflows/help-command.yml
> -    if: ${{ !github.event.issue.pull_request && contains(github.event.comment.body, '/help') && github.actor != 'asyncapi-bot'}}
I added back the syntax expression format `{{`` and `}}` on the `create_help_comment_issue`.

2022-01-19 12:55 UTC, KhudaDad414 commented on .github/workflows/if-nodejs-release.yml
> -      - '**-release'
@smoya thanks! can you change https://github.com/asyncapi/.github/blob/41d14e04e38d75a6123f898d894e36e42dfde72a/.github/workflows/help-command.yml#L13 to `${{ github.event.issue.pull_request && contains(github.event.comment.body, '/help' ) && github.actor != 'asyncapi-bot' }}` for consistency?

2022-01-19 13:38 UTC, smoya commented on .github/workflows/if-nodejs-release.yml
> -      - '**-release'
done!

2022-01-19 14:37 UTC, KhudaDad414 approved these changes

2022-01-19 14:37 UTC, KhudaDad414 commented on .github/workflows/help-command.yml
> +    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/help' && github.actor != 'asyncapi-bot') }}
```suggestion
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/help') && github.actor != 'asyncapi-bot' }}
```

2022-01-19 14:41 UTC, KhudaDad414 approved these changes
LGTM!

2022-01-19 14:43 UTC, smoya commented
Thanks folks for the review!

Anything else to add @derberg ? 🚀

2022-01-20 09:51 UTC, derberg approved these changes

2022-01-20 13:22 UTC, smoya commented
/rtm

2022-01-20 13:22 UTC, merged