Workflow for markdown link check
asyncapi/.github pull request #141
Opened 2022-03-05 05:22 UTC by Namyalg

**Description**
This PR resolves the first requirement mentioned [here](https://github.com/asyncapi/.github/issues/92)
- On a pull request the link checker action will be run
- In the config file, the links of the form https://github.com/nodejs/node/commit are omitted

**Related issue(s)**
Fixes #92

2022-03-05 05:23 UTC, Namyalg commented
On approval I will add the workflow to run on schedule with slack integration

2022-03-07 05:20 UTC, KhudaDad414 requested changes
great work. added some comments :)

2022-03-07 05:20 UTC, KhudaDad414 commented on .github/workflows/link-check.yml
> +  pull_request:
what about limiting the types of `pull_request` event that trigger this workflow?
I would suggest having:
- synchronize
- ready_for_review
- opened
- reopened

2022-03-07 05:20 UTC, KhudaDad414 commented on .github/workflows/link-check.yml
> +        check-modified-files-only: 'no'
since it runs only on PRs, I guess it makes sense to have `check-modified-files-only: 'yes'`. the other workflow will check all of the links periodically right?

2022-03-07 10:23 UTC, Namyalg commented on .github/workflows/link-check.yml
> +        check-modified-files-only: 'no'
I have made the necessary changes
For periodic checking of links, I wanted to know if a slack integration as mentioned in the issue #92 is required, and if so how I can go about with that

2022-03-07 13:43 UTC, KhudaDad414 commented
@Namyalg we are already doing it in different workflows. you can take here https://github.com/asyncapi/.github/blob/master/.github/workflows/issues-prs-notifications.yml

2022-03-07 13:51 UTC, Namyalg commented
Got it, I plan to  add a job that will run periodically to perform the link check, and report if there erroneous/broken link.
Should the cron job run every day/week ?

2022-03-07 14:21 UTC, KhudaDad414 commented
@Namyalg IMO it would be better to have a separate workflow for this for the sake of maintainability. and weekly checks seems reasonable.

2022-03-07 14:24 UTC, Namyalg commented
Alright, thanks for the confirmation

2022-03-08 11:24 UTC, derberg commented
@Namyalg please keep in mind that @alequetzalli wanted to get these scheduled notifications into `#13_docs` folder. 

This is `SLACK_DOCS_CHANNEL` env variable with required token

2022-03-08 11:25 UTC, derberg commented on .github/workflows/link-check.yml
> +        config-file: 'config.json'
maybe you could make config name more specific, to make it clear it is related to links validation?

2022-03-08 12:46 UTC, Namyalg commented on .github/workflows/link-check.yml
> +        config-file: 'config.json'
Alright, I will make the change

2022-03-08 12:50 UTC, Namyalg commented
Yep, I saw the integration with gha has been added to that channel, will send weekly updates to the docs channel

2022-03-09 02:44 UTC, alequetzalli commented
> @Namyalg please keep in mind that @alequetzalli wanted to get these scheduled notifications into `#13_docs` folder.
> 
> This is `SLACK_DOCS_CHANNEL` env variable with required token

yes this ☝️ 😀

2022-03-09 02:46 UTC, alequetzalli submitted a review, later dismissed
I see nothing on my end from a markdown perspective to change/edit, so I would rely on @derberg and the rest on this PR to determine when you're ready to merge, @Namyalg 😀

2022-03-09 14:10 UTC, Namyalg commented
@KhudaDad414 , Along with the cron schedule, should I also remove the dead/unreachable links present in the current repository ?

2022-03-09 15:00 UTC, KhudaDad414 commented
@Namyalg I don't think that would be necessary. PR owner will deal with it.

2022-03-09 15:26 UTC, Namyalg commented
Alright, I have added the action to check links once every week and report it on slack.
Currently, I have included the `workflow_dispatch` event to enable testing the workflow manually in `link-check-cron.yml`

2022-03-09 17:20 UTC, KhudaDad414 commented on .github/workflows/link-check-cron.yml
> +      uses: 8398a7/action-slack@v3
@Namyalg just to check, this step will send a status report regardless of the status, right? I mean will it send a message even if the job doesn't find any broken links?

2022-03-09 17:32 UTC, Namyalg commented on .github/workflows/link-check-cron.yml
> +      uses: 8398a7/action-slack@v3
Currently, it does send a message regardless of the status.
I can change it to `if failure()`

2022-03-10 03:07 UTC, Namyalg commented
Including the `config-file` is providing erroneous results, I will be removing the file and in the future, if there is a need it can be included in the root of the repository

2022-03-11 04:45 UTC, KhudaDad414 approved these changes
LGTM! 🚀  Great effort @Namyalg. 🙇  let's wait for @derberg 's review.

2022-03-14 08:58 UTC, derberg requested changes
I do not see you using `config-file` property in the markdown links validator.

did you test it in some test repo, can you share link to some logs, I'd like to see how it works in action, what logs are being created on success and on failure

2022-03-14 08:58 UTC, derberg commented on .github/workflows/link-check-cron.yml
> +    - uses: actions/checkout@master
we should never use actions from default branch, sure risky and can cause headaches 😄 please use latest release instead

2022-03-14 13:06 UTC, Namyalg commented
@derberg , https://github.com/Namyalg/.github/runs/5537524751?check_suite_focus=true
This is a sample run of the workflow


![image](https://user-images.githubusercontent.com/53875297/158177722-49321fa4-3ef0-4f24-b702-6d6ec6fba31c.png)
The message reported on slack

2022-03-14 13:09 UTC, Namyalg commented on .github/workflows/link-check-cron.yml
> +    - uses: actions/checkout@master
I will change it to `actions/checkout@v3`

2022-03-17 13:28 UTC, derberg commented
@Namyalg yeah, I think we can resign from config file for now

2022-03-17 13:41 UTC, Namyalg commented
@derberg, I will remove the file
Are there any additions/deletions that need to be done to the logs?

2022-03-18 03:43 UTC, Namyalg commented
- It checks only for external links, does not perform the check for relative paths
- The `status code` returned is 200, when there is a redirect as in case of the example

2022-03-18 06:25 UTC, derberg commented
@Namyalg cool! so I guess you can remove the config, adjust `actions/checkout` to not use `master` and we are ready to merge, right?

2022-03-18 14:26 UTC, Namyalg commented
@derberg , all changes have been made
It is ready to be merged!

2022-03-18 14:54 UTC, derberg requested changes
one 2 tiny improvements needed

2022-03-18 14:54 UTC, derberg commented on .github/workflows/link-check-pr.yml
> +
```suggestion
```

please remove empty line

2022-03-18 14:54 UTC, derberg commented
@KhudaDad414 anything from your side?

2022-03-18 15:34 UTC, KhudaDad414 reviewed
LGTM! let's merge it :)

2022-03-18 15:38 UTC, Namyalg commented on .github/workflows/link-check-pr.yml
> +    runs-on: ubuntu-latest
I have made the changes

2022-03-23 12:50 UTC, derberg commented
@Namyalg hey, are you there around in our Slack in case we need your help if some strange alerts will start popping up? 😅

2022-03-23 12:54 UTC, Namyalg commented
Yep, Im on slack

2022-03-28 07:20 UTC, derberg approved these changes

2022-03-28 07:20 UTC, derberg commented
/rtm

2022-03-28 07:21 UTC, merged