ci: add a workflow to build docker images on pull requests
asyncapi/.github pull request #147
Opened 2022-03-22 10:22 UTC by HarshCasper

**Description**

- Add a workflow to build Docker images on PRs
- Implement CI caching using the Cache backend API

**Related issue(s)**

https://github.com/asyncapi/server-api/issues/50

2022-03-22 10:22 UTC, HarshCasper commented
cc: @smoya @derberg

2022-03-23 14:12 UTC, derberg requested changes
looks good 🚀 
just left few comments

2022-03-23 14:12 UTC, derberg commented on .github/workflows/if-docker-pr-testing.yml
> +        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
why not using `v3` but specific commit?

2022-03-23 14:12 UTC, derberg commented on .github/workflows/if-docker-pr-testing.yml
> +        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
why not using `v1` but specific commit?

2022-03-24 03:03 UTC, alequetzalli commented
This sounds amazing, @HarshCasper!

I approve it, but obviously looks like @derberg and other folks will have more feedback on the code to make sure it works 🎉

2022-03-24 03:03 UTC, alequetzalli approved these changes

2022-03-28 08:45 UTC, magicmatatjahu commented on .github/workflows/if-docker-pr-testing.yml
> +        name: Build and push Docker image
We don't push image.

```suggestion
        name: Build Docker image
```

2022-04-12 08:22 UTC, derberg commented
@HarshCasper yo, do you plan to continue working on this?

2022-04-13 01:54 UTC, HarshCasper commented on .github/workflows/if-docker-pr-testing.yml
> +  IMAGE_NAME: ${{ github.repository }}
Yes, it would. Workflow-level `env` is supported. Please refer: https://docs.github.com/en/actions/learn-github-actions/environment-variables#:~:text=The%20entire%20workflow%2C%20by%20using%20env%20at%20the%20top%20level%20of%20the%20workflow%20file.

2022-04-13 08:39 UTC, derberg commented on .github/workflows/if-docker-pr-testing.yml
> +  IMAGE_NAME: ${{ github.repository }}
oh cool!

different docs, different answers

cc @KhudaDad414 look, I think some time ago we wanted to use it this way but we only found docs that said that only on job level it is possible

2022-04-13 08:42 UTC, derberg commented
@magicmatatjahu @smoya do we want it only on server-api for now? or `generator` too?

@HarshCasper please add new step to https://github.com/asyncapi/.github/blob/master/.github/workflows/global-replicator.yml that is replicating this new workflow only to repositories with `docker` topic

2022-04-13 08:44 UTC, magicmatatjahu commented
@derberg Atm we can "test" workflow only in the `server-api` repo, but long term we should run it on every repo where we publish docker image.

2022-04-13 08:53 UTC, KhudaDad414 commented on .github/workflows/if-docker-pr-testing.yml
> +  IMAGE_NAME: ${{ github.repository }}
I guess since the variable is used in `with:` part which ends up in the runner itself it should be good. but in the previous case, I tried to use it in the workflow syntax itself (in `if:` part) which runs outside of the runner (by GitHub Actions somewhere) and it wasn't working 🤔

2022-04-14 09:20 UTC, derberg commented
ok then, just added `docker` topic to `server-api`

2022-04-25 17:39 UTC, HarshCasper commented
Done @KhudaDad414!

2022-04-26 11:08 UTC, derberg commented
@HarshCasper fyi below left todo to get this merged

> @HarshCasper please add new step to https://github.com/asyncapi/.github/blob/master/.github/workflows/global-replicator.yml that is replicating this new workflow only to repositories with docker topic

2022-04-26 12:14 UTC, derberg commented on .github/workflows/global-replicator.yml
> +        github_token: ${{ secrets.GH_TOKEN }}
```suggestion
        github_token: ${{ secrets.GH_TOKEN }}
        topics_to_include: docker
```

we want this workflow to be replicated only to repos that have `docker` topic, which is `server-api` repo so far

2022-04-26 16:48 UTC, merged