Validate workflow schema
asyncapi/.github pull request #159
Opened 2022-04-23 04:23 UTC by Namyalg

**Description**

This PR consists of a script and a workflow that validates the yml schema of a workflow file

**Related issue(s)**
Issue #150 

This is sample run on [2 erroneous files ](https://github.com/Namyalg/.github/runs/6137835602?check_suite_focus=true)

2022-04-23 09:37 UTC, Namyalg commented
I have created a workflow file and this is the log on [2 erroneous workflow files](https://github.com/Namyalg/.github/runs/6137960820?check_suite_focus=true)

2022-04-25 16:01 UTC, derberg requested changes
Thanks a lot. I made few suggestions. Once you apply them, please show workflow in action in some test repo

2022-04-25 16:01 UTC, derberg commented on .github/workflows/validate-workflow-schema.yml
> +      - name: Identify changed yml files # Identifies files added, modified, copied or renamed
please use `actions/github-script@v4`

you can just `require` your script inside like https://github.com/asyncapi/spec/blob/master/.github/workflows/new-spec-release.yml#L59-L61

2022-04-26 03:05 UTC, Namyalg commented on .github/scripts/validate-workflow-schema.js
> +    if(getFileExtension(filename) === 'yml'){
👍

2022-04-26 03:06 UTC, Namyalg commented on .github/scripts/validate-workflow-schema.js
> +        'https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json'
yep, that's better

2022-04-26 03:07 UTC, Namyalg commented on .github/scripts/validate-workflow-schema.js
> +            console.log("The workflow in " + filename + " has an invalid schema");
Thanks for this, I was looking out for something similar, as a workflow that passes even on failure may not be very intuitive to the user

2022-04-26 03:07 UTC, Namyalg commented on .github/workflows/validate-workflow-schema.yml
> +      - name: Identify changed yml files # Identifies files added, modified, copied or renamed
Alright

2022-04-26 03:08 UTC, Namyalg commented on .github/workflows/validate-workflow-schema.yml
> +  push:
👍

2022-04-26 15:10 UTC, Namyalg commented on .github/workflows/validate-workflow-schema.yml
> +      - name: Identify changed yml files # Identifies files added, modified, copied or renamed
@derberg, Is this a replacement for this ?https://github.com/Namyalg/.github/blob/eafbd93f29d67c9c03d824a5d23413455ea2cfc9/.github/workflows/validate-workflow-schema.yml#L32

2022-04-26 15:21 UTC, derberg commented on .github/workflows/validate-workflow-schema.yml
> +      - name: Identify changed yml files # Identifies files added, modified, copied or renamed
yes, don't call code like this directly but through the `github-script` action

2022-04-27 04:09 UTC, Namyalg commented
@derberg , In case 2 yml files are created during a PR, and the first one fails, currently the action will stop at the first failed file. Is it a good idea to do this or validate both the files and then report the error ?

2022-04-27 07:25 UTC, derberg commented
@Namyalg best developer experience would be to validate all the files and throw error at the end of validation with list of all affected files, end related errors

just `catch` errors into a `Map` where you keep filename and error and then at the end, if `size` is bigger than `0` just throw error with all details

2022-04-27 14:42 UTC, Namyalg commented
Okay, working on this

2022-04-27 18:20 UTC, Namyalg commented
I have made the changes suggested

This is a [sample](https://github.com/Namyalg/.github/runs/6198894344?check_suite_focus=true) workflow run

Few points : 
- The JSON schema has been stored in a file in `scripts` . I was facing some issues due to the async call to axios, hence fs.readFileSync has been used
- On encountering errors in file(s), the name of the file and the log is shown. The workflow fails (using actions/@core)
- Without installing `actions/@core`, an package not found error occurred (As it was earlier mentioned that actions/@core is a part of the actions/github-script action)

2022-05-09 09:16 UTC, derberg requested changes
looking better, left some comments, please have a look

2022-05-09 09:16 UTC, derberg commented on .github/workflows/validate-workflow-schema.yml
> +  workflow_dispatch:
can be removed, we do not need to run it on demand, only on PR I think

2022-05-09 09:16 UTC, derberg commented on .github/workflows/validate-workflow-schema.yml
> +            npm install @actions/core
it is ok to leave it explicitly here, otherwise, you would have to pass it into your script like `script(files, core)`

but yeah, in case of this workflow where we anyway need to install some dependencies, it is fine

just huge request from my side: just like in case of `ajv@8.11.0` please also make sure to lock other dependencies to a specific version

2022-05-09 09:16 UTC, derberg commented on .github/workflows/validate-workflow-schema.yml
> +        uses: tj-actions/changed-files@v18.7
can we make sure it check only changes in files in `.github/workflows` ?

2022-05-09 09:16 UTC, derberg commented on .github/workflows/validate-workflow-schema.yml
> +  pull_request:
please narrow triggering only in case PR modifies something in the `.github/workflows` in `yml` or `yaml` files

ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths

2022-05-09 09:16 UTC, derberg commented on .github/workflows/validate-workflow-schema.yml
> +name: Schema Validation
```suggestion
name: GitHub Workflows Schema Validation
```

2022-05-09 11:58 UTC, Namyalg commented on .github/workflows/validate-workflow-schema.yml
> +            npm install @actions/core
Alright

2022-05-10 19:13 UTC, Namyalg commented
@derberg the changes have been made

2022-05-11 11:08 UTC, derberg commented on .github/workflows/validate-workflow-schema.yml
> +        - '**.yml'
can't we do `.github/workflows` there too?

2022-05-11 11:21 UTC, Namyalg commented on .github/workflows/validate-workflow-schema.yml
> +        - '**.yml'
Yes, the path is now updated to `.github/workflows/**.yml` and `.github/workflows/**.yaml`

2022-05-11 17:51 UTC, derberg commented
@KhudaDad414 anything from your side. I'm ok with the current shape, so from my point of view examples can be removed, but maybe you wanna have a look into logs too

2022-09-20 06:57 UTC, derberg commented
@KhudaDad414 hey, can you have a look?

2022-09-20 08:13 UTC, KhudaDad414 commented on .github/scripts/validate-workflow-schema.js
> +    let schema = fs.readFileSync('.github/scripts/yml-schema.json', {encoding:'utf8', flag:'r'});
@Namyalg can't we use the [schema store](https://json.schemastore.org/github-workflow.json) hosted file instead of our own copy? I don't think it is advisable from a maintainability point of view since **schema store** is actively maintaining this file.

2022-09-21 08:04 UTC, Namyalg commented on .github/scripts/validate-workflow-schema.js
> +    let schema = fs.readFileSync('.github/scripts/yml-schema.json', {encoding:'utf8', flag:'r'});
As in read directly from the URL and compare?

2022-09-21 08:09 UTC, KhudaDad414 commented on .github/scripts/validate-workflow-schema.js
> +    let schema = fs.readFileSync('.github/scripts/yml-schema.json', {encoding:'utf8', flag:'r'});
Yes, I have done some tests [here](https://github.com/KhudaDad414/.github/blob/bdb585cda6833a3a57ac7b7276892920238d6f07/.github/scripts/validate-workflow-schema.js) and it works like a charm.

2022-10-03 17:15 UTC, derberg commented
@Namyalg hey, do you need some help?

2022-10-09 06:21 UTC, Namyalg commented
Hey @derberg, I was wondering how I should go about changing my code
Do we want to include [this version](https://github.com/KhudaDad414/.github/blob/bdb585cda6833a3a57ac7b7276892920238d6f07/.github/scripts/validate-workflow-schema.js#L36) of the function or just replace the [first line](https://github.com/Namyalg/.github/blob/6c6498a11be74250619272d8f632941da4a27765/.github/scripts/validate-workflow-schema.js#L9) and read from the URL instead ?

2022-10-10 09:06 UTC, derberg commented
@Namyalg hey, best is just to remove `yml-schema.json` and read it from URL provided by @KhudaDad414

2022-10-10 09:13 UTC, derberg commented
@Namyalg I see that you are already installing `axios` as dependency, so you can use it

2022-10-19 11:58 UTC, derberg commented
@Namyalg hey, need a hand?

2022-10-22 13:40 UTC, Namyalg commented
Hey @derberg, working on the changes

2022-11-14 09:33 UTC, derberg commented
@Namyalg fyi there are still 2 not addressed comments

2023-01-06 01:33 UTC, Namyalg commented
Hey @derberg, apologize for the delay.
The script to validate schemas reads from the URL, based on the [reference script](https://github.com/KhudaDad414/.github/blob/bdb585cda6833a3a57ac7b7276892920238d6f07/.github/scripts/validate-workflow-schema.js) written by @KhudaDad414

2023-01-12 15:13 UTC, derberg commented
@Namyalg no worries 👍🏼 

@KhudaDad414 can you please have another look?

2023-01-13 09:37 UTC, KhudaDad414 submitted a review, later dismissed
Let's see this in action :) thanks @Namyalg 👏

2023-01-13 09:53 UTC, Namyalg commented
Shall I delete the test file [one](https://github.com/Namyalg/.github/blob/validate-workflow-schema/sample.yml) and [two](https://github.com/Namyalg/.github/blob/validate-workflow-schema/.github/workflows/sample.yml) ?

2023-01-13 09:55 UTC, KhudaDad414 commented
@Namyalg sure, since we do not need them.

2023-01-13 10:00 UTC, Namyalg commented
Done with the deletions 👍

2023-03-02 15:58 UTC, KhudaDad414 commented on .github/workflows/validate-workflow-schema.yml
> +            npm install @actions/core@1.8.0
hey @Namyalg, do you want to make this change? let's not keep this PR open for a year 😆

2023-03-03 12:19 UTC, Namyalg commented on .github/workflows/validate-workflow-schema.yml
> +            npm install @actions/core@1.8.0
Yes, I will fix it asap

2023-03-14 14:27 UTC, derberg commented on .github/workflows/validate-workflow-schema.yml
> +            npm install @actions/core@1.8.0
I don't think it has been addressed

2023-03-14 14:33 UTC, derberg requested changes
We are almost ready to go, but since the creation of this PR, some changes were introduces in project in regards to "global" files.

- You need to add this new workflow explicitly to https://github.com/asyncapi/.github/blob/master/.github/workflows/global-replicator.yml#L134 list
- You need to move JS script to [workflows/scripts](https://github.com/asyncapi/.github/tree/master/.github/workflows/scripts) and add there to the script a comment on what is this script used for. If for my other comment, you go with `package.json` and `package-lock.json` then you will need to add there a folder for the script and related files

Lemme know if you need more explanation

2023-03-14 18:29 UTC, Namyalg commented
Okay @derberg , will look into it

2023-03-27 13:00 UTC, derberg commented
@Namyalg need help?

2023-04-05 18:21 UTC, derberg commented
@Namyalg I hope you plan to complete it as you spent a lot of time on it.

We have one contributor that is willing to complete it for you, but I want to make sure you are ok with it

2023-04-05 18:58 UTC, Namyalg commented
Hello @derberg , working on it. 
I would like to collaborate with the other contributor.

2023-04-06 09:53 UTC, derberg commented
@14Richa I know you were interested to help with this one
@Namyalg thanks for quick response 🙏

2023-04-08 08:23 UTC, 14Richa commented
Hey @Namyalg, let me know if you need any help. You can ping me on slack as well. :) 

Always happy to help!!

2023-04-08 08:24 UTC, 14Richa commented
Thanks, @derberg.  I will get in touch with @Namyalg and make the pr ready to merge asap together. :)

2023-04-19 09:57 UTC, derberg commented
any success? maybe we should just start from scratch?

we need this validation as we have lots of workflows, and I caused some errors recently just because of syntax error in a workflow 🙃 😄

2023-04-23 18:36 UTC, Namyalg commented
Yes, I think we can start from scratch @derberg 
Where should I get started ?

2023-04-24 11:54 UTC, derberg commented
@Namyalg if you want to continue with this one, no need to start from scratch. There are minor stuff left. I suggested from scratch in case you want to let it go.

did you have a change to sync with @14Richa and get some help? Both of you are in our Slack

2023-06-19 08:52 UTC, KhudaDad414 commented
closing since it has been done here: https://github.com/asyncapi/.github/pull/238

2023-06-19 08:52 UTC, closed without merging