feat: add error comment in lint-pr-title.yml
asyncapi/.github pull request #175
Opened 2022-07-29 16:15 UTC by Krishks369

I have added feature in the lint-pr-title.yml file to comment on the lint errors in the title while PR is created

 **Three scenarios are there for the workflow**

1.  When the PR title is not in the correct format i.e when it is apart from titles like `feat`, `fix` etc. It works like it has in this [PR](https://github.com/Krishks369/.github/pull/16) .

2. When the PR title is not found or the PR subject starts in capital, then it works like in this [PR](https://github.com/Krishks369/.github/pull/17)

3. When the lint is corrected after the comment, the comment is then deleted from the PR, as mentioned in https://github.com/marocchino/sticky-pull-request-comment

Although the action used for linting the title is https://github.com/amannn/action-semantic-pull-request  I have forked and used this feature before it got merged in the main action. So temporarily it uses https://github.com/Krishks369/action-semantic-pull-request.

2022-08-22 16:10 UTC, derberg requested changes
I left some comments

2022-08-22 16:10 UTC, derberg commented on .github/workflows/lint-pr-title.yml
> +          header: comment
you tested it, right?

2022-09-21 07:56 UTC, derberg commented
@Krishks369 hey man, need a hand?

2022-09-23 16:59 UTC, closed without merging

2023-03-16 13:34 UTC, sambhavgupta0705 commented
Hey @derberg ,do we need to refine this PR also?