Update lint-pr-title.yml
asyncapi/.github pull request #182
Opened 2022-09-23 17:09 UTC by Krishks369

Added all the suggestions by @derberg 

- a welcome message with the error message 
- comments are correct now

For examples visit following two links
- [pr 1](https://github.com/Krishks369/.github/pull/16)  
- [pr 2](https://github.com/Krishks369/.github/pull/19)

2022-09-26 07:08 UTC, derberg requested changes

2022-09-26 07:08 UTC, derberg commented on .github/workflows/lint-pr-title.yml
> +                   We require all PRs to follow Conventional Commits specification. More details 👇🏼
```suggestion
                   We require all PRs to follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/). More details 👇🏼
```

2022-09-26 07:08 UTC, derberg commented on .github/workflows/lint-pr-title.yml
> +          header: comment
maybe we should make headers more unique? like instead of `comment` do `pr-title-lint-error`? you know, in case we like this solution with comments and start reusing it for other scenarios, so these do not override each other?

```suggestion
          header: pr-title-lint-error
```

2022-09-26 07:08 UTC, derberg commented on .github/workflows/lint-pr-title.yml
> +          header: comment
```suggestion
          header: pr-title-lint-error
```

2022-09-26 07:08 UTC, derberg commented on .github/workflows/lint-pr-title.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
I guess you should change it back to GH_TOKEN, right?

2022-09-26 07:10 UTC, derberg commented on .github/workflows/lint-pr-title.yml
> +                   ```
leave it as a normal message formatted with markdown, only the error part put in code

2022-09-26 07:14 UTC, derberg commented
@Krishks369 did you test somewhere the comment delete functionality, can you show it working somewhere?

2022-09-26 07:29 UTC, Krishks369 commented
> @Krishks369 did you test somewhere the comment delete functionality, can you show it working somewhere?

if you check the pr 2 in the description, the comment has been deleted

2022-09-26 07:33 UTC, derberg commented
@Krishks369 Perfect ❤️

2022-09-26 09:18 UTC, derberg commented
@Krishks369 look what we have here https://github.com/amannn/action-semantic-pull-request/releases/tag/v4.6.0 ❤️ 

just please do not use `@4.6.0` but `@505e44b4f33b4c801f063838b3f053990ee46ea7`

2022-09-28 15:04 UTC, derberg reviewed
@Krishks369 all is perfect, I only have one concern

https://github.com/asyncapi/.github/pull/182/files#diff-4ca33f7807c23352bf46868ad75e37a351f2f21417aab29ca4e0554ab77db5e6R18 condidtion

so what will happen in this workflow if the PR is submitted by `asyncapi-bot` for example? ideally, no comment about conventional commits should be added.

2022-09-28 16:13 UTC, derberg approved these changes
@Krishks369 amazing work mate, like really!!! it is not just a great improvement in PR title validation workflow. The thing is that it is a first workflow where we have bot commenting enabled in the workflow and I bet we will reuse it!!!

2022-09-28 16:22 UTC, derberg requested changes

2022-09-28 17:20 UTC, derberg approved these changes

2022-09-28 17:21 UTC, derberg commented
/rtm

2022-09-28 17:21 UTC, merged