feat: Updated workflow with more skippable PRs
asyncapi/.github pull request #214
Opened 2023-03-09 15:11 UTC by dante381

**Description**
-Added 8 other PR titles to each `if` statement in testing workflow.

**Related issue(s)**

Resolves #200

2023-03-09 17:27 UTC, KhudaDad414 commented on .github/workflows/if-docker-pr-testing.yml
> +          )"
@dante381 have you tested these statements in your fork to see if it works?

2023-03-09 17:45 UTC, dante381 commented on .github/workflows/if-docker-pr-testing.yml
> +          )"
No i didnt. I dont know how to test it.

2023-03-10 09:17 UTC, KhudaDad414 commented on .github/workflows/if-docker-pr-testing.yml
> +          )"
you have a few options here. either you can use [act](https://github.com/nektos/act) or create another brach, remove the testing logic and replace them with some logging message like `echo "Yay it's working..."` 😆. then you can just change the `allcontributor` and/or `asyncapi-bot` with your own username and check if it actually works as expected.

2023-03-10 11:29 UTC, dante381 commented
I have tested it using `act` and it raised a few parsing errors due to extra `)` and double quotations `""`.
I have fixed it and there are no other errors.

[Resulting output of the test](https://github.com/asyncapi/.github/files/10941515/test_result.txt)

2023-03-10 16:37 UTC, KhudaDad414 commented on .github/workflows/if-docker-pr-testing.yml
> +            (github.actor == 'asyncapi-bot' && !(
```suggestion
          !github.event.pull_request.draft && !(
            (github.actor == 'asyncapi-bot' && (
```

2023-03-10 16:38 UTC, KhudaDad414 commented on .github/workflows/if-go-pr-testing.yml
> +            (github.actor == 'asyncapi-bot' && !(
```suggestion
          !github.event.pull_request.draft && !(
            (github.actor == 'asyncapi-bot' && (
```

2023-03-10 16:38 UTC, KhudaDad414 commented on .github/workflows/if-go-pr-testing.yml
> +            (github.actor == 'asyncapi-bot' && !(
```suggestion
          !github.event.pull_request.draft && !(
            (github.actor == 'asyncapi-bot' && (
```

2023-03-10 17:03 UTC, dante381 commented on .github/workflows/if-docker-pr-testing.yml
> +            (github.actor == 'asyncapi-bot' && !(
made the changes

2023-03-10 17:03 UTC, dante381 commented on .github/workflows/if-go-pr-testing.yml
> +            (github.actor == 'asyncapi-bot' && !(
made the changes

2023-03-10 17:03 UTC, dante381 commented on .github/workflows/if-go-pr-testing.yml
> +            (github.actor == 'asyncapi-bot' && !(
made the changes

2023-03-10 17:09 UTC, KhudaDad414 commented on .github/workflows/if-go-pr-testing.yml
> +            (github.actor == 'asyncapi-bot' && !(
can you remove that extra `!` as well?

2023-03-10 17:42 UTC, dante381 commented on .github/workflows/if-go-pr-testing.yml
> +            (github.actor == 'asyncapi-bot' && !(
Done

2023-03-13 09:35 UTC, KhudaDad414 requested changes
PS: you can just click on the `commit suggestion` button and GitHub will apply the suggested changes for ya. 😀

2023-03-13 09:35 UTC, KhudaDad414 commented on .github/workflows/if-docker-pr-testing.yml
> +              startsWith(github.event.pull_request.title, 'ci: update global workflows') ||
the `!` after `'asyncapi-bot' &&` should be removed.

```suggestion
          !github.event.pull_request.draft && !(
            (github.actor == 'asyncapi-bot' && (
              startsWith(github.event.pull_request.title, 'ci: update global workflows') || 
```

2023-03-13 09:35 UTC, KhudaDad414 commented on .github/workflows/if-go-pr-testing.yml
> +              startsWith(github.event.pull_request.title, 'ci: update global workflows') ||
```suggestion
          !github.event.pull_request.draft && !(
            (github.actor == 'asyncapi-bot' && (
              startsWith(github.event.pull_request.title, 'ci: update global workflows') || 
```

2023-03-13 09:35 UTC, KhudaDad414 commented on .github/workflows/if-go-pr-testing.yml
> +              startsWith(github.event.pull_request.title, 'ci: update global workflows') ||
```suggestion
          !github.event.pull_request.draft && !(
            (github.actor == 'asyncapi-bot' && (
              startsWith(github.event.pull_request.title, 'ci: update global workflows') || 
```

2023-03-14 11:23 UTC, KhudaDad414 approved these changes
LGTM!

2023-03-14 11:27 UTC, KhudaDad414 commented
/rtm

2023-03-14 11:27 UTC, merged

2023-03-14 17:45 UTC, derberg commented
great job @dante381 !

I checked on one PR that was added after we merged this, and all good, there are no bugs and on [normal PRs](https://github.com/asyncapi/modelina/actions/runs/4417737051/jobs/7743862790) nothing is skipped, but of a certain title is there like https://github.com/asyncapi/modelina/actions/runs/4415237144/jobs/7737945176 the skip takes place. Thanks!!!