Add a new github action which logs all the reactions in prs and issues
asyncapi/.github pull request #220
Opened 2023-03-28 09:37 UTC by 14Richa

**Description**
 A GitHub action that calls API on every issue and PR and provides logs of reaction on each PR and issue.

**Related issue(s)**

Resolves: #41

2023-03-29 14:51 UTC, derberg commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +        run: npm install @octokit/rest
did you have to install it? afaik `actions/github-script@v4` makes sure you have access to library by default and you do not have to pass auth secrets as it reads secrets by default 🤔

2023-03-29 14:51 UTC, derberg commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +                state: 'all',
how does it work? it is part of octokit that makes you pull all issues without paging?

2023-03-29 14:51 UTC, derberg commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +                      labels: ['more than 5 reactions'],
I guess that if we add this label, we can also filter by this label, to not perform `addLabels` on all issues but only those that do not have a label?

2023-03-29 14:51 UTC, derberg commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +on:
instead of reacting on event that issue or PR was created we need two triggers imho:
- cron, that runs once a week, I think enough
- workflow dispatch that allows for manual trigger in case someone do not want to wait until next cron trigger

thoughts?

2023-03-29 15:08 UTC, 14Richa commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +on:
Sounds good to me. @derberg 

It was the first prototype so I simply triggered it with PR and issue. But definitely, we can add a cron job to the workflow.

2023-03-29 15:11 UTC, 14Richa commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +                      labels: ['more than 5 reactions'],
Yes, you are correct. Adding a label to the issues and pull requests that have more than 5 reactions would allow us to filter.

2023-03-29 15:17 UTC, 14Richa commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +on:
@derberg, I have added the cron job which runs at midnight on Sundays, I have also enabled the workflow dispatch which triggers manually, and removed the earlier triggers.

2023-03-29 15:50 UTC, derberg commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +                state: 'all',
I think you missed this question

2023-03-29 15:53 UTC, derberg commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +                const labelsResponse = await github.issues.listLabelsOnIssue({
oh, we need to query for list of labels, this info is not part of `issuesResponse.data` or accessible in some kind of easier way without additional API call?

asking case I waned us to filter by `!labels.includes('more than 5 reactions')` to limit numer of calls, and not increase them 😄

2023-03-30 10:30 UTC, derberg commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +            const octokit = new Octokit({ auth: '${{ secrets.GITHUB_TOKEN }}'});
this is not needed, that is the whole beauty of using `actions/github-script`

https://github.com/actions/github-script says that out of the box you have `github A pre-authenticated [octokit/rest.js](https://octokit.github.io/rest.js) client with pagination plugins`

and then have a look at how you should do pagination -> https://github.com/actions/github-script#welcome-a-first-time-contributor

2023-03-30 11:04 UTC, derberg reviewed
few final questions

also, is there a repo where you test it that code works?

2023-03-30 11:04 UTC, derberg commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +        uses: actions/checkout@v2
use v3 please, we will soon have to update all our workflows to use it too

2023-03-30 11:04 UTC, derberg commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +          github-token: ${{ secrets.GITHUB_TOKEN }}
is it still needed?

2023-03-30 11:04 UTC, derberg commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +                  labels: ['more than 5 reactions'],
`more than 5 reactions` I'm wondering if this is good label name, like what if we at some point of time say " maybe we should only monitor if there is more than 10 emotions

maybe we can have a better, and also "no spaces" label name?

2023-03-30 11:17 UTC, 14Richa commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +                  labels: ['more than 5 reactions'],
@derberg , how about `reactions-5plus` ?

2023-03-30 12:26 UTC, 14Richa commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +          github-token: ${{ secrets.GITHUB_TOKEN }}
Yes

2023-03-30 13:35 UTC, derberg commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +                  labels: ['more than 5 reactions'],
what about my comment about problem with using specific number?

so basically have a label that do not refer to the amount of emotions but the fact that it requires attention as many community members are involved

2023-03-30 13:38 UTC, derberg commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +          github-token: ${{ secrets.GITHUB_TOKEN }}
but this is a generic token, the default one GitHub Actions have access to, and `github-scripts` claims that `github` client is preauthorised, so my assumption is that they access the token on their own from secrets, no?

their docs say:
```
Note that github-token is optional in this action, and the input is there in case you need to use a non-default token.
```

2023-03-30 13:51 UTC, 14Richa commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +                  labels: ['more than 5 reactions'],
Few more options IMHO: 
1. `community-attention` 
2. `community-review` 
3. `community-discussion`

2023-03-31 08:26 UTC, 14Richa commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +          github-token: ${{ secrets.GITHUB_TOKEN }}
In the docs, If we want to print the available attributes of context we don't need a token but if we want to comment on PR or add a label we do need `GITHUB_TOKEN`. Here is the link: https://github.com/actions/github-script/tree/releases/v4

Also in one of our [yaml](https://github.com/asyncapi/.github/blob/master/.github/workflows/welcome-first-time-contrib.yml#L22), we are using a token. 

If we don't use the token we are getting: `Error: Unhandled error: HttpError: Resource not accessible by integration`

2023-03-31 09:34 UTC, derberg commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +          github-token: ${{ secrets.GITHUB_TOKEN }}
ok, thanks for explanation 🙂

2023-03-31 09:37 UTC, derberg commented
@KhudaDad414 can you also have a look at this workflow?

I was thinking if maybe we should first add it to only one repo, to see how it works 🤔

2023-03-31 10:49 UTC, thulieblack commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +                  labels: ['more than 5 reactions'],
This sounds cool, so if issues have a certain amount of emojis, they'll be added to the dashboard. Are there particular criteria for such issues or particular emojis that'll be used?

2023-03-31 10:58 UTC, KhudaDad414 requested changes
Do we have an estimation of how many API calls will it make for all repos?

2023-03-31 10:58 UTC, KhudaDad414 commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +    - cron: "0 0 * * 0" # Run at midnight on Sundays
Not a fan of midnight. A random time would be a lot better.
```suggestion
    - cron: "0 13 * * 0" # Run at 1 PM on Sundays
```

2023-03-31 11:15 UTC, KhudaDad414 commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +        uses: actions/github-script@v4
```suggestion
        uses: actions/github-script@v6
```

2023-03-31 11:22 UTC, KhudaDad414 commented
@derberg I tested this in my fork and everything seems to be in order so I don't see the point. 🤔

2023-04-03 14:41 UTC, derberg commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +                  labels: ['more than 5 reactions'],
@thulieblack dashboard would be basically a link to https://github.com/issues?q=is%3Aopen+org%3Aasyncapi+sort%3Aupdated-desc+label%3A%22community-attention%22+ for now. So list of all issues from all AsyncAPI. I do not know how to build a link that would point to all PRs

and it will list issues that have `community-attention` label. And this label will be added to every issue and PR that has more than 5 emojis (any) added. 

makes sense?

maybe we should increase to more than 10?

2023-04-03 14:41 UTC, derberg commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +                  labels: ['more than 5 reactions'],
later we can extend https://www.asyncapi.com/community/dashboard maybe 🤔

2023-04-11 10:24 UTC, thulieblack commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +                  labels: ['more than 5 reactions'],
Let's extend the emojis to more than 10. 
So for building a PR "dashboard" don't we need to use GitHub API to collect all PRs from all repos?

2023-04-11 10:28 UTC, derberg commented on .github/workflows/check-reactions-on-pr-and-issues.yml
> +                  labels: ['more than 5 reactions'],
@thulieblack PR and issues, yes, definitely need to call the API. We have that logic in place already https://www.asyncapi.com/community/dashboard in `Hot Topics`. Just when we start adding `community-attention` labels, we should probably extend `Hot Topics` of just have another view. This is anyway not in scope for this PR. That is a separate discussion

2023-04-11 10:55 UTC, 14Richa commented
> Do we have an estimation of how many API calls will it make for all repos?

Hey Khuda, yes we do have. 

One API call per repo, then as many calls as `issues with reactions > 10` we have in a repo, and the same with PR.

2023-04-13 18:32 UTC, 14Richa commented
> @14Richa it is actually more. Single request fetch no more than 100 issues (I don't know what is the default per_page but max is 100) so in one repo like website it can be even 15 calls.

I agree. I guess we'd have to loop over the paginated results. 

> in UI I can query for issues that have a certain amount of reactions: https://github.com/asyncapi/website/issues?q=is%3Aissue+reactions%3A%3E5
so if REST API does not enable you to do this, maybe GraphQL API will?

I think the GitHub GraphQL API does not provide a direct way to filter issues based on the number of reactions.

>one small concern I have is that reactions that we change for now in this PR are the reactions on issue, but there can be reactions to the individual comment.

Agree with this. I modified the GitHub action on my [local repo to test it](https://github.com/14Richa/testRepo/blob/main/.github/workflows/ci-test1.yml#L38-L62). It works fine but it increases the API calls and the filtering still happens client side.

2023-04-13 19:05 UTC, derberg commented
> I agree. I guess we'd have to loop over the paginated results.

pagination plugin that you use there already handles that, just make sure page size is max

> Agree with this. I modified the GitHub action on my [local repo to test it](https://github.com/14Richa/testRepo/blob/main/.github/workflows/ci-test1.yml#L38-L62). It works fine but it increases the API calls and the filtering still happens client side.

yeah, I bet the amount of calls multiply a lot

> I think the GitHub GraphQL API does not provide a direct way to filter issues based on the number of reactions.

I just tried `search` and worked well:

```
query { 
  search(query: "org:asyncapi reactions:>10", type: ISSUE, first:100) { 
    issueCount
    edges{
      node {
        ... on Issue {
          url
        }
      }
    }
  }
}
```

result
```
{
  "data": {
    "search": {
      "issueCount": 6,
      "edges": [
        {
          "node": {
            "url": "https://github.com/asyncapi/website/issues/903"
          }
        },
        {
          "node": {
            "url": "https://github.com/asyncapi/cli/issues/251"
          }
        },
        {
          "node": {
            "url": "https://github.com/asyncapi/brand/issues/1"
          }
        },
        {
          "node": {
            "url": "https://github.com/asyncapi/spec/issues/618"
          }
        },
        {
          "node": {}
        },
        {
          "node": {
            "url": "https://github.com/asyncapi/spec/issues/94"
          }
        }
      ]
    }
  }
}
```

but now I'm thinking.... @KhudaDad414 aren't you actually doing it in your community dashboard for hot issues?

with such search query we do not need the action to run in all repos, but just in one. Still no solution for comments....

2023-04-13 19:12 UTC, 14Richa commented
> I just tried search and worked well

I see, I didn't know about that way. I had tried and couldn't find a neat way to add filter from the nested `totalCount`.
```
query {
  search(type: ISSUE, query: "") {
    issueCount
    edges {
      node {
        number
        title
        reactions(first: 100) {
          totalCount
        }
      }
    }
  }
}

    ```

2023-04-14 13:48 UTC, KhudaDad414 commented
@derberg, yes we are using `search` for the dashboard and it is awesome (very low points for api calls).

@14Richa have you checked https://github.com/asyncapi/website/blob/master/scripts/dashboard/issue-queries.js ? there are some queries that might help. also since you are going to query the reactions on the comments as well, it can consume more points which need to be tested.

2024-02-21 14:37 UTC, closed without merging