ci: workflow to validate YAML schema of workflow files
asyncapi/.github pull request #238
Opened 2023-05-15 06:24 UTC by 14Richa

**Description**

This pull request includes two components - a script and a workflow - that are designed to validate the YAML schema of a workflow file.

**Related issue(s)**
#150

2023-05-15 08:48 UTC, KhudaDad414 commented
Hey @14Richa, can you also add the testing information on how it has been tested and where to the description?

2023-05-15 14:54 UTC, 14Richa commented
> Hey @14Richa, can you also add the testing information on how it has been tested and where to the description?

Hey @KhudaDad414, I have updated the description. Please have a look when you get time!! :)

2023-05-19 11:41 UTC, KhudaDad414 requested changes
Let a comment.

2023-05-19 11:41 UTC, KhudaDad414 commented on .github/workflows/global-replicator.yml
> +          patterns_to_include: .github/workflows/scripts,.github/workflows/automerge-for-humans-add-ready-to-merge-or-do-not-merge-label.yml,.github/workflows/add-good-first-issue-labels.yml,.github/
I think having `validate-wokflow-schema.yml` in this repo is enough since this is the gateway for most workflows. 😄

2023-05-19 12:25 UTC, KhudaDad414 requested changes

2023-05-19 12:25 UTC, KhudaDad414 commented on .github/scripts/validate-workflow-schema.js
I think this should be in `workflows/scripts`

2023-05-19 12:25 UTC, KhudaDad414 commented on .github/scripts/validate-workflow-schema.js
> +      console.error(validator.errors);
the name of the invalid file should be included in logs.

2023-05-19 12:25 UTC, KhudaDad414 commented on .github/workflows/validate-workflow-schema.yml
> +      - main
```suggestion
      - master
```

2023-05-19 12:25 UTC, KhudaDad414 commented on .github/workflows/validate-workflow-schema.yml
> +        run: ls -alh node_modules
```suggestion
      - name: Install Dependencies
        run: npm install yaml-lint ajv axios js-yaml
```

2023-05-30 08:55 UTC, KhudaDad414 commented on .github/workflows/validate-workflow-schema.yml
> +          node ./scripts/validate-workflow-schema.js
can you make sure that this relative link work fine?
I my testing here https://github.com/KhudaDad414/.github/actions/runs/5119498352/jobs/9204831837 it doesn't work unless I change it to : `node .github/workflows/scripts/validate-workflow-schema.js`

2023-05-30 09:07 UTC, 14Richa commented on .github/workflows/validate-workflow-schema.yml
> +          node ./scripts/validate-workflow-schema.js
I just checked in my testRepo and it's working fine : https://github.com/14Richa/testRepo/actions/runs/5119632693/jobs/9205141265

2023-05-30 10:06 UTC, KhudaDad414 commented on .github/workflows/validate-workflow-schema.yml
> +          node ./scripts/validate-workflow-schema.js
It is because you have the `scripts` folder in your root directory. here the path should be `.github/workflows/scripts/validate-workflow-schema.js` I think 🤔

2023-05-30 10:46 UTC, 14Richa commented on .github/workflows/validate-workflow-schema.yml
> +          node ./scripts/validate-workflow-schema.js
Make sense. I have updated the pr.

2023-05-31 12:14 UTC, derberg commented on .github/workflows/validate-workflow-schema.yml
> +          node .github/workflows/scripts/validate-workflow-schema.js
do we need a separate js file, can't we inline it here?

2023-06-02 12:47 UTC, 14Richa commented on .github/workflows/validate-workflow-schema.yml
> +          node .github/workflows/scripts/validate-workflow-schema.js
@KhudaDad414, thoughts?

2023-06-02 12:49 UTC, KhudaDad414 commented on .github/workflows/validate-workflow-schema.yml
> +          node .github/workflows/scripts/validate-workflow-schema.js
I agree with @derberg. TBH, It took me some time to debug the issue with the script not being found in directory. 😆 
Inlining would help a lot.

2023-06-02 13:43 UTC, KhudaDad414 commented on .github/workflows/validate-workflow-schema.yml
> +          async function validateWorkflows() {
Do we need this function? we can just write the javascript here without declaring a function. 🤔

2023-06-02 14:12 UTC, 14Richa commented on .github/workflows/validate-workflow-schema.yml
> +          async function validateWorkflows() {
While it's possible to exclude the function declaration, using a function brings benefits like code reusability, modularity, better error handling, and improved readability. It enhances the maintainability and extensibility of the GitHub Actions workflow. That's why the function was kept in the code.

2023-06-04 12:31 UTC, KhudaDad414 requested changes

2023-06-04 12:31 UTC, KhudaDad414 commented on .github/workflows/validate-workflow-schema.yml
> +        run: |
Hey @14Richa, It won't work since you are writing javascript as a shell script. please use the `github-script` action. it should look something like this:
https://github.com/asyncapi/.github/blob/31b1ebe08b5ac7c0781bcaecc4ad768fc7d90436/.github/workflows/welcome-first-time-contrib.yml#L20

2023-06-04 13:01 UTC, 14Richa commented on .github/workflows/validate-workflow-schema.yml
> +        run: |
Agreed, @KhudaDad414. My apologies, it slipped from my mind. Nevertheless, I have just updated the code and tested it in my [testRepo](https://github.com/14Richa/testRepo/actions/runs/5169210294/jobs/9311320915).

2023-06-05 09:26 UTC, KhudaDad414 approved these changes
@14Richa Great effort. 👍

2023-06-05 09:28 UTC, KhudaDad414 requested changes
can you also document the new `get-workflows-validation` in the README file as we have discussed?

2023-06-05 16:24 UTC, 14Richa commented
> can you also document the new `get-workflows-validation` in the README file as we have discussed?

Could you please let me know which README.md file is most relevant for adding the documentation for the `get-workflows-validation`? This repository contains three different README.md files.

2023-06-06 09:29 UTC, KhudaDad414 commented
@14Richa since we are not currently documenting these topics anywhere I think it would be great to add them to https://github.com/asyncapi/.github/blob/master/README.md for now.

a table with the topics and which workflows they replicate or what they do would be amazing. :)
we currently have a few:
`golang`,`nodejs`,`get-global-node-release-workflows`, `get-global-releaserc` etc...

2023-06-06 10:09 UTC, 14Richa commented
> @14Richa since we are not currently documenting these topics anywhere I think it would be great to add them to https://github.com/asyncapi/.github/blob/master/README.md for now.
> 
> a table with the topics and which workflows they replicate or what they do would be amazing. :) we currently have a few: `golang`,`nodejs`,`get-global-node-release-workflows`, `get-global-releaserc` etc...

Sounds good. I have added a demo table that contains workflow details. We can update it with information about all the other workflows as well.

2023-06-06 10:16 UTC, KhudaDad414 commented on README.md
> +| get-workflows-validation | YAML schema validation | Validates the YAML schema of a workflow file |
```suggestion
| Topic to include | Workflows you will get | Description |
| --- | --- | --- |
| `get-workflows-validation` | [validate-workflow-schema](.github/workflows/validate-workflow-schema.yml) | Validates the YAML schema of a workflow files in your repository |
```
What about this format? 🤔

2023-06-06 10:19 UTC, 14Richa commented on README.md
> +| get-workflows-validation | YAML schema validation | Validates the YAML schema of a workflow file |
This looks cool with more clarity. I will update the rest of the documentation in a similar manner. Thank you, Khuda! :)

2023-06-08 09:20 UTC, KhudaDad414 approved these changes

2023-06-08 09:24 UTC, KhudaDad414 commented on .github/workflows/global-replicator.yml
> +        bot_branch_name: bot/update-files-from-global-repo
```suggestion
    if: startsWith(github.repository, 'asyncapi/')
    name: Replicate workflow schema validation to repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Replicating file
        uses: derberg/manage-files-in-multiple-repositories@beecbe897cf5ed7f3de5a791a3f2d70102fe7c25
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          patterns_to_include: .github/workflows/validate-workflow-schema.yml
          topics_to_include: get-workflows-validation
          committer_username: asyncapi-bot
          committer_email: info@asyncapi.io
          commit_message: "ci: update of files from global .github repo"
          bot_branch_name: bot/update-files-from-global-repo 
```

2023-06-08 09:25 UTC, KhudaDad414 approved these changes

2023-06-08 09:26 UTC, KhudaDad414 commented
Thanks 🙇 @14Richa.

2023-06-08 09:26 UTC, KhudaDad414 commented
/rtm

2023-06-08 09:27 UTC, merged