feat : added ping-for-attention command to notify the reviewers
asyncapi/.github pull request #239
Opened 2023-05-18 15:36 UTC by Priyansh61

**Description**
The PR adds the functionality to use `/pfa`or `/ping-for-attention`.
The functionality is achieved by
- Gets the PR data on which we use the command.
- Gets the list of requested_reviewers.
- Checks for reviewers who have made a review.
- Finally pings the reviewrs by adding a comment who have not reviewed.

**Proof of Work**

https://github.com/asyncapi/website/assets/96513964/32352875-0ef7-4e33-8989-c4de00f9ee1e

**Related issue(s)**

Resolves #211

2023-05-22 09:12 UTC, derberg requested changes
hey, thanks for the PR, please have a look at the bot message and failing logs and update the PR title 🙏🏼

2023-05-25 02:58 UTC, alequetzalli commented
This will be useful for people like me 😅

2023-05-30 07:42 UTC, derberg commented on .github/workflows/help-command.yml
> +                    - `/ping-for-attention` or `/pfa` or `/ptal` - This comment will add a comment to the PR asking for attention from the reviewrs who have not reviewed the PR yet.
I think we should just go with one way, and `ptal` is the best one as it is known short, just do `ptal` and longer version which probably is something like `please take a look` (probably something to check with urban dictionary)

2023-05-30 08:42 UTC, Priyansh61 commented on .github/workflows/help-command.yml
> +                    - `/ping-for-attention` or `/pfa` or `/ptal` - This comment will add a comment to the PR asking for attention from the reviewrs who have not reviewed the PR yet.
Done

2023-06-12 15:48 UTC, KhudaDad414 submitted a review, later dismissed
LGTM!

2023-06-26 11:35 UTC, derberg reviewed
@Priyansh61 hey, you added to help command info about `rerequest` and `review` but the PR contains only support for `ptal` 🤔

2023-06-26 11:39 UTC, derberg commented
unless the plan is to have it here, to not add it in https://github.com/asyncapi/.github/pull/243/files to not face merge conflicts later? so we basically wait for https://github.com/asyncapi/.github/pull/243/ until it is approved and we merge both PRs together?

@KhudaDad414 as you were in review when I was out, did you discuss that these new workflows need to be added to https://github.com/asyncapi/.github/blob/master/.github/workflows/global-replicator.yml#L141?

2023-06-26 12:07 UTC, KhudaDad414 commented
@derberg my bad, totally forgot that. 🤦

2024-03-11 16:25 UTC, derberg commented
@KhudaDad414 since a lot for work is done, but contributor is not around, maybe you can just commit directly to his for what is missing and we can merge?

2024-03-12 14:14 UTC, KhudaDad414 submitted a review, later dismissed
@derberg everything looks good from my side. 👍

2024-03-27 10:30 UTC, derberg submitted a review, later dismissed
🚀

2024-04-02 18:49 UTC, KhudaDad414 approved these changes

2024-04-02 18:56 UTC, KhudaDad414 commented
/rtm

2024-04-02 19:07 UTC, merged