ci: update MAINTAINERS.yaml based on CODEOWNERS changes
asyncapi/.github pull request #248
Opened 2023-07-12 15:03 UTC by 14Richa

**Description**

This PR updates the MAINTAINERS.yaml file based on the changes made in the CODEOWNERS file. The workflow takes the repository name as input and adds it to the MAINTAINERS.yaml file. When a new code owner is added, a corresponding maintainer object is created in the MAINTAINERS.yaml file with the repository name added to the object.
Similarly, when a code owner is removed, the corresponding maintainer object is removed from the MAINTAINERS.yaml file. The removal process checks if the maintainer has any other repositories before removing them from the MAINTAINERS.yaml file.

I have tested this workflow on my testRepo by adding a new code owner, and the MAINTAINERS.yaml file was updated with the new code owner object and repository name. Here are the logs from the workflow: https://github.com/14Richa/testRepo/actions/runs/5529240136/jobs/10087030814
Similarly, when a code owner is removed MAINTAINERS.yaml file was updated accordingly with the maintainer object removed from the file. Here are the logs from the workflow: https://github.com/14Richa/testRepo/actions/runs/5529277200/jobs/10087118152

2023-07-12 15:28 UTC, derberg requested changes
yo, initial review for now, main algorithm review once we get basics fixed

2023-07-12 15:28 UTC, derberg commented on .github/workflows/update-maintainers.yml
> +          node-version: '14'
```suggestion
        uses: actions/setup-node@v3
        with:
          node-version: '16'
```

always latest please

2023-07-12 15:28 UTC, derberg commented on .github/workflows/update-maintainers.yml
> +            const repoName = process.env.REPO_NAME;
sorry but why this, and also `Get repository name` step if you can do what you already did here: https://github.com/asyncapi/community/pull/750/files#diff-8ba49e6b37c137810bad8252fc74cb498dbeae5bc4650e947719905455ac7492R46

`const repo = context.repo.repo;`

2023-07-12 15:28 UTC, derberg commented on .github/workflows/update-maintainers.yml
> +          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} master
push alone will not work, you need to do the same as you did with this workflow: https://github.com/asyncapi/community/blob/master/.github/workflows/update-website-tsc.yml#L48-L51

create PR, as changes in repos can be done only through PRs

btw also makes sense to add slack alert

2023-07-12 15:28 UTC, derberg commented on .github/workflows/update-maintainers.yml
> +        uses: actions/checkout@v2
version, consistency 😛 every time you copy/paste and do not check, a kitty dies 😄

2023-07-12 15:54 UTC, 14Richa commented on .github/workflows/update-maintainers.yml
> +        uses: actions/checkout@v2
Thanks for the reminder! :p 
Understood, I'll make sure to maintain consistency and double-check all details in the future.

2023-07-17 10:00 UTC, KhudaDad414 reviewed
getting syntax error 
https://github.com/KhudaDad414/.github/actions/runs/5574259435/jobs/10182640765

2023-07-17 10:06 UTC, 14Richa commented
> getting syntax error https://github.com/KhudaDad414/.github/actions/runs/5574259435/jobs/10182640765

Fixed it. Please check now!

2023-07-18 08:32 UTC, KhudaDad414 requested changes
Isn't this PR supposed to open a pull request to the community repo? I see it applies the changes locally.

2023-07-18 08:32 UTC, KhudaDad414 commented on .github/workflows/update-maintainers.yml
> +            const prCodeowners = fs.readFileSync('./previous_state/CODEOWNERS', 'utf8');
Insn't these variables names a little confusing? PR and MAIN are basically the same here. can't we name these just like the branches? something like `previousCodeowners` and `currentCodeowners`

2023-07-18 08:32 UTC, KhudaDad414 commented on .github/workflows/update-maintainers.yml
> +            const prUsernames = extractGitHubUsernames(prCodeowners);
same here about naming...

2023-07-18 08:32 UTC, KhudaDad414 commented on .github/workflows/update-maintainers.yml
> +              if (!existingMaintainer) {
```suggestion
              const maintainerExists = maintainers.find(maintainer => maintainer.github === username);
              if (!maintainerExists) {
```

2023-07-18 08:32 UTC, KhudaDad414 commented on .github/workflows/update-maintainers.yml
> +                console.log('Maintainer', username, 'already exists. Skipping addition.');
what about cases when maintainer does exists but they are being added as maintainer to another repo. shouldn't we add the current repo the their repo list?

2023-07-18 09:42 UTC, 14Richa commented
> Isn't this PR supposed to open a pull request to the community repo? I see it applies the changes locally.

Thank you for bringing this to my attention. I have updated the workflow. Now it creates a new branch and pushes the changes there. Subsequently, it opens a pull request for these changes to be reviewed and merged into the master branch in the community repo.

2023-07-18 16:52 UTC, derberg requested changes
some cleanup needed

2023-07-18 16:52 UTC, derberg commented on .github/workflows/update-maintainers.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```suggestion
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
```

2023-07-18 16:52 UTC, derberg commented on .github/workflows/update-maintainers.yml
> +        env:
I think you can do `env` on job level and then just reuse the `env` like in like 91 instead what we have in line 166

2023-07-18 16:52 UTC, derberg commented on .github/workflows/update-maintainers.yml
> +        run: npm install @octokit/rest
why do you need to install it, it is for sure part of `actions/github-script@v6` action

![Screenshot 2023-07-18 at 18 38 29](https://github.com/asyncapi/.github/assets/6995927/fe03d71f-32bb-420f-bf0b-7b6c487f67a0)

and rest client there is already preauthenticated so you do not need code like

```
const { Octokit } = require("@octokit/rest");

            const octokit = new Octokit({
              auth: process.env.GITHUB_TOKEN,
              request: {
                fetch: (url, options) => fetch(url, options)
              }
            });
```

2023-07-18 16:52 UTC, derberg commented on .github/workflows/update-maintainers.yml
> +            function extractGitHubUsernames(content) {
we need to make this regex "comments"-proof

some codeowners files have comments likekhttps://github.com/asyncapi/spec/blob/master/CODEOWNERS and there can be a situation that in the comment there is also `@` and a github handle, but commented out

2023-07-18 16:52 UTC, derberg commented on .github/workflows/update-maintainers.yml
> +              const twitterUsername = data.twitter_username;
better first, early just exclude bots, no need to call for twitter info from GH API if we have bot-usecase

2023-07-18 16:52 UTC, derberg commented on .github/workflows/update-maintainers.yml
> +              const index = maintainers.findIndex(maintainer => maintainer.github === username);
why you need different approach here, other than in case of addition, why `findIndex`

2023-07-20 09:05 UTC, KhudaDad414 reviewed
Looks great. 👍

2023-07-20 09:05 UTC, KhudaDad414 commented on .github/workflows/update-maintainers.yml
> +          token: ${{ secrets.GITHUB_TOKEN }}
If you have to use a token, then please use the `GH_TOKEN` for consistency across this file.

2023-07-20 09:28 UTC, derberg reviewed
2 comments only

2023-07-20 09:28 UTC, derberg commented on .github/workflows/update-maintainers.yml
> +                  console.log('Maintainer', username, 'already exists and already has the repo. Skipping addition.');
```suggestion
                  console.log(`Maintainer ${username} already exists and already has the repo. Skipping addition.`);
```

2023-07-20 09:28 UTC, derberg commented on .github/workflows/update-maintainers.yml
> +                    const index = maintainers.indexOf(maintainer);
did you test it well and you sure it works fine

I usually use indexOf for simple types, and for objects it is not that obvious -> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality#comparing_objects

@KhudaDad414 thoughts?

2023-07-20 10:52 UTC, 14Richa commented on .github/workflows/update-maintainers.yml
> +                    const index = maintainers.indexOf(maintainer);
@derberg, I did test it. Here are the logs: https://github.com/14Richa/testRepo/actions/runs/5610049235/jobs/10264525094
Codeowner was successfully removed from MAINTAINERS.yaml file.

2023-07-20 11:31 UTC, derberg commented on .github/workflows/update-maintainers.yml
> +                    const index = maintainers.indexOf(maintainer);
but it is risky, as `indexOf` do not actually check the content but references, super risky in any future refactoring. I recommend changing to `findIndex`

2023-07-25 11:38 UTC, derberg commented on .github/workflows/update-maintainers.yml
> +name: Update MAINTAINERS.yaml
```suggestion
name: Update MAINTAINERS.yaml in community repo
```

2023-07-25 11:38 UTC, derberg approved these changes
LGTM

before we merge, we need to manually add it to `generator` repo for testing

2023-07-25 11:40 UTC, 14Richa commented
> before we merge, we need to manually add it to generator repo for testing 

@derberg , should I raise PR in the generator repo?

2023-07-26 11:56 UTC, KhudaDad414 approved these changes
LGTM!

2023-07-27 11:09 UTC, derberg submitted a review, later dismissed
lgtm

2023-07-27 11:09 UTC, derberg commented
/dnm

2025-03-20 09:42 UTC, closed without merging