feat: add autoupdate-workflow
asyncapi/.github pull request #262
Opened 2023-11-21 16:46 UTC by Shurtu-gal

**Description**

- Replaces previous auto-update workflow with the current one.
- Uses an action developed by me :- https://github.com/marketplace/actions/autoupdate-fork-action
- The action currently runs on push to branches and updates PRs pointing to it and having `autoupdate` label in it.

**Related issue(s)**
Fixes #227

2024-02-21 14:53 UTC, derberg requested changes
I'm not 100% sure how it works, also please share examples where you tested it.

I'm confused because:
- I do not understand why autoupdate workflow had to be removed
- what is the difference between `update` and `autoupdate` (cause you left autoupdate). Is it that `autoupdate` you use once and then it is always triggered, and `update` you need to pass every time you wanna trigger update?
- in short explain why previous action did not work and what technical change you do in your action that now bot token will be able to push to fork

2024-02-21 16:44 UTC, Shurtu-gal commented
@derberg as was discussed over slack, to not consume too much action minutes right now auto-update is only enabled for comments like `\u` or `/update`. Hence there is no need of filtering based on labels.

[Successful run](https://github.com/Shurtu-gal/autoupdate-fork-action/actions/runs/7992039025) [The related PR](https://github.com/Shurtu-gal/autoupdate-fork-action/pull/1)

Labels were meant for filtering in case of mass updates, [like in this case](https://github.com/Shurtu-gal/autoupdate-fork-action)

Also, I had removed the previous one as I this one was sufficient for both tasks, but before we do so we have to consider amount of action minutes it will take. Furthermore, GH API limit may also be reached.

### Why wasn't the previous one working?
Because the API used by it requires admin access for the updation. Meanwhile, I am [this mutation](https://docs.github.com/en/graphql/reference/mutations#updatepullrequestbranch) which basically uses a merge PR already created by GitHub (Yeah, I know it sounds unreal 😆), and applies it on top of the HEAD, this was custom made for PR branches.

2024-02-21 18:25 UTC, derberg commented
the problem with saving minutes is that we have a huge amount of bot-created PRs, that quite often require autoupdating

one example: https://github.com/asyncapi/asyncapi-react/pull/924 -> by default autoupdate is added and the bot merges master in like a charm

2024-02-28 19:43 UTC, Shurtu-gal commented
/autoupdate

2024-02-28 20:12 UTC, Shurtu-gal commented
/update

2024-02-28 20:13 UTC, Shurtu-gal commented
@derberg 
A successful run on comment:- https://github.com/ash17290/asyncapi-github/actions/runs/8086468906
A Successful run on push:- https://github.com/ash17290/asyncapi-github/actions/runs/8086440737

Note that only labelled PRs are auto-updated rest have to be manually done.

2024-03-11 16:52 UTC, derberg commented on .github/workflows/automerge-for-humans-add-ready-to-merge-or-do-not-merge-label.yml
> +                       PRO-TIP: Add a comment to your PR with the text: \`/u\` or \`/update\` and our bot will take care of updating the branch in the future. The only requirement for this to work is
```suggestion
                       PRO-TIP: To request an update from the upstream branch, simply comment \`/u\` or \`/update\` and our bot will handle the update operation promptly.
                       
                       The only requirement for this to work is to enable [Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) option in your PR. Also the update will not work if your fork is located in an organization, not under your personal profile.
```

2024-03-28 10:14 UTC, Shurtu-gal commented
@derberg The refactoring has been done.

2024-04-03 07:10 UTC, derberg commented on .github/workflows/autoupdate-fork.yml
> +      github.event_name == 'issue_comment' && (
this is always this even name, 

instead you need something like:
```
github.event.issue.pull_request && 
      github.event.issue.state != 'closed' && 
```

example: https://github.com/asyncapi/.github/blob/master/.github/workflows/automerge-for-humans-add-ready-to-merge-or-do-not-merge-label.yml#L18-L19

2024-04-03 09:02 UTC, Shurtu-gal commented on .github/workflows/autoupdate.yml
> +# This action is centrally managed in https://github.com/asyncapi/.github/
Yeah, the git hashes may be different, there has been no changes though.

2024-04-03 09:21 UTC, Shurtu-gal commented on .github/workflows/autoupdate-fork.yml
> +                const comment = `@${context.actor} I don't have permissions to update this PR. Please ask the PR author to check the "Allow edits from maintainers" checkbox in the PR settings.`;
Added it.

2024-04-03 09:22 UTC, Shurtu-gal commented on .github/workflows/help-command.yml
> +                    - \`/update\` or \`/u\` - This comment will update the PR with the latest changes from the target branch. Unless there is a merge conflict or it is a draft PR.`
Added.

2024-04-04 13:02 UTC, derberg commented on .github/workflows/autoupdate-fork.yml
> +name: Autoupdate PR branches from fork
don't want to be picky but we need to handle naming here with caution so we do not confuse it with autoupdate command

this one should be `Update PR branches from fork`, same filename and job name like `autoupdate-pr` should be `update-pr`

2024-04-04 13:21 UTC, Shurtu-gal commented on .github/workflows/autoupdate-fork.yml
> +                const comment = `@${context.actor} I don't have permissions to update this PR. Please ask the PR author to check the "Allow edits from maintainers" checkbox in the PR settings. Anothe
Thanks will do so.

2024-04-04 13:51 UTC, Shurtu-gal commented
> also in error messages for user, we do not write anything about merge conflicts, that in case of merge conflicts it will also not work

Added that as well.

2024-04-18 10:33 UTC, derberg approved these changes
great stuff!!!

2024-04-18 10:45 UTC, derberg commented
/rtm

2024-04-18 10:46 UTC, merged

2024-04-18 19:03 UTC, Shurtu-gal commented
/help

2024-04-18 19:04 UTC, Shurtu-gal commented
/update