ci: implemment pagination
asyncapi/.github pull request #266
Opened 2023-12-17 09:24 UTC by Min2who

i have not found a way to test this (PS: sorry for that)

**Description**
Each co-author appear in a new line and implement pagination 
**Related issue(s)** 
Resolves #263

2023-12-18 11:07 UTC, KhudaDad414 requested changes
TBH I am not a fan of writing this action in bash. it is hard to maintain ( I don't speak bash). 😆 
can you rewrite in in almighty js?

2023-12-18 15:34 UTC, Min2who commented
> TBH I am not a fan of writing this action in bash. it is hard to maintain ( I don't speak bash). 😆 can you rewrite in in almighty js?

i am too not a big fan of bash but as @smoya had mentioned in the issue to use some bash thats why i have used bash but no problem i am converting it too js

2023-12-18 16:16 UTC, smoya commented
> > TBH I am not a fan of writing this action in bash. it is hard to maintain ( I don't speak bash). 😆 can you rewrite in in almighty js?
> 
> i am too not a big fan of bash but as @smoya had mentioned in the issue to use some bash thats why i have used bash but no problem i am converting it too js 
> cc @KhudaDad414 

Totally no strong opinion on using bash or any language of our preference TBH. So 👍 on my side.

2023-12-18 16:30 UTC, Min2who commented
@KhudaDad414 @smoya should i rewrite this in js or not

2023-12-18 17:58 UTC, derberg commented
@Min2who please rewrite to JS as we have a lot of experience with it and it will be much better to maintain long term.

please use https://github.com/actions/github-script action that already have pagination related plugins added so writing such script will be much better DX and also much readable ❤️ 

so one step will be just getting data from GitHub API (by default afaik response will be stored as part of output that you will be able to access from another step https://github.com/actions/github-script?tab=readme-ov-file#reading-step-results). And in another step you will construct a commit message.

such approach will make maintenance much better + will make is easier to debug in future

2023-12-19 01:13 UTC, smoya commented
> i am too not a big fan of bash

As @derberg stated, +1 to use JS. From the very moment this is not gonna be a simple one liner as it was, it will become very hard to maintain.

2023-12-21 18:02 UTC, Min2who commented
@KhudaDad414 @derberg @smoya can you suggest me some way to test this actions locally

2023-12-22 13:36 UTC, KhudaDad414 commented
@Min2who actions are a little hard to test especially this one. I would suggest testing the script you write separately and making sure it gets what you want. testing the entire workflow is a little more challenging, you may need to test it on your fork. I think testing the script here suffices.

2024-01-14 10:47 UTC, Min2who commented
i have updated this action using the github [octokit.paginate]() pluging and have test this in my local fork action [this](https://github.com/Min2who/.github/actions/runs/7518627857/job/20466164310?pr=4)

2024-01-15 10:08 UTC, KhudaDad414 requested changes

2024-01-15 10:08 UTC, KhudaDad414 commented on .github/workflows/automerge-for-humans-merging.yml
> -# Purpose of this workflow is to allow people to merge PR without a need of maintainer doing it. If all checks are in place (including maintainers approval) - JUST MERGE IT!
can you restore these comments? I think these are useful.

2024-01-15 10:08 UTC, KhudaDad414 commented on .github/workflows/automerge-for-humans-merging.yml
> +        uses: pascalgn/automerge-action@v0.15.6
```suggestion
        uses: pascalgn/automerge-action@22948e0bc22f0aa673800da838595a3e7347e584 #v0.15.6 https://github.com/pascalgn/automerge-action/releases/tag/v0.15.6
```

we use the commit instead of release tag for security reasons.

2024-01-15 10:08 UTC, KhudaDad414 commented on .github/workflows/automerge-for-humans-merging.yml
> +          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
I don't think `GITHUB_TOKEN` has permission to merge PRs. please use the `GH_TOKEN`.

```suggestion
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
```

2024-01-15 17:02 UTC, Min2who commented
made the changes

cc @KhudaDad414

2024-01-16 12:09 UTC, KhudaDad414 submitted a review, later dismissed
LGTM! please wait for @derberg's review. 🙇

2024-01-21 13:19 UTC, Min2who commented
> LGTM! please wait for @derberg's review. 🙇

waiting 🙇‍♂️
cc @derberg

2024-02-21 15:10 UTC, derberg requested changes
@Min2who hey, left some comments how you can improve the action

can you share some example where did you test it, a test run?

2024-03-11 16:55 UTC, derberg commented
@utnim2 did you see my other comments?

2024-03-11 16:57 UTC, utnim2 commented
> @utnim2 did you see my other comments?

ahh sorry , working on it

2024-03-11 21:26 UTC, utnim2 commented
Done the reviewed changes

The test of this action [here](https://github.com/utnim2/CI-CD-test/actions/runs/8239797327/job/22533830137) 

cc @derberg @KhudaDad414

2024-03-27 10:32 UTC, derberg commented on .github/workflows/automerge-for-humans-merging.yml
> +        run: npm install @octokit/core @octokit/plugin-paginate-rest @octokit/rest cross-fetch
what about my comment that it can be removed?

2024-03-28 14:56 UTC, utnim2 commented on .github/workflows/automerge-for-humans-merging.yml
> +        run: npm install @octokit/core @octokit/plugin-paginate-rest @octokit/rest cross-fetch
removed it, sorry for it

2024-04-18 10:28 UTC, derberg commented
@utnim2 lgtm but there were some changes done since initial implementation, can you show your changes somewhere in action, in some test repo? I can help if you need someone to open a PR in your repo, and then you make edits to make sure it works

2024-07-07 15:42 UTC, alechkos commented on .github/workflows/automerge-for-humans-merging.yml
> +                });
### Simplification and correction of the way to access the repo information:

```suggestion
                const { owner, repo } = context.repo;
                const pull_number = context.issue.number;
                
                const commitsResponse = await github.paginate("GET /repos/{owner}/{repo}/pulls/{pull_number}/commits", {
                  owner,
                  repo,
                  pull_number,
                  per_page: 100
                });
```

2024-07-07 15:46 UTC, alechkos commented on .github/workflows/automerge-for-humans-merging.yml
> +            await getCoAuthors();
### Correct way to set the output in the `Get List of authors` step:
```suggestion
            const coAuthors = await getCoAuthors();
            core.setOutput("value", coAuthors);
```

2025-03-20 09:42 UTC, derberg commented
already solved in another PR

2025-03-20 09:42 UTC, closed without merging