Evaluateed github ations workflow files
asyncapi/.github pull request #268
Opened 2024-01-14 13:38 UTC by mhmohona

**Description**

- Updated GitHub Actions workflow to pass potentially untrusted data through environment variables as per GitHub's security hardening guidelines.
- Ensured that titles used in email notifications are now set via environment variables to prevent script injection attacks.

**Related issue(s)**

#257

2024-01-15 09:29 UTC, KhudaDad414 commented on .github/workflows/notify-tsc-members-mention.yml
> -            const sendEmail = require('./.github/workflows/scripts/mailchimp/index.js');
@mhmohona why are we removing the `sendEmail` import? 🤔

2024-01-16 11:19 UTC, mhmohona commented
I have a concern on it.

After running the actionlit for this repo it was the output - 
![image](https://github.com/asyncapi/.github/assets/14244685/1fcfc525-a367-4b88-af5a-9b29223f29c8)

For first 2 errors, when I tested the scripts in https://rhysd.github.io/actionlint/, it didnt catch them.

If i address them, then both from actionlit online site and IDE I get error.

Should I address 1st 2 errors then? Or probably its a bug. :3

2024-01-17 13:00 UTC, KhudaDad414 commented on .github/workflows/validate-workflow-schema.yml
>        - name: Install Dependencies
you can remove the rest of the steps. since `actionlint` will validate the file as well.

2024-02-21 15:17 UTC, derberg requested changes
Amazing initiative, thanks!!!

Can you refactor to not download linter binary but use a dedicated github action 

https://github.com/raven-actions/actionlint

?

2024-03-27 10:33 UTC, derberg commented
@mhmohona do you plan to continue with this one?

2024-04-30 09:05 UTC, derberg commented
@mhmohona do you plan to continue with this one or should we ask community to continue?

2024-05-13 09:45 UTC, derberg reviewed
will you address the linter issues that are now shown in PR?

2024-05-13 09:45 UTC, derberg commented on .github/workflows/notify-tsc-members-mention.yml
> +            sendEmail('${{github.event.comment.html_url}}', process.env.DISCUSSION_TITLE);
do you modify it because the linter complained?

I wonder then why `github.event.comment.html_url` did not have to be refactored as well 🤔

2024-05-13 09:45 UTC, derberg commented on .github/workflows/validate-workflow-schema.yml
>          uses: actions/checkout@v2
```suggestion
        uses: actions/checkout@v4
```

2024-05-13 09:50 UTC, derberg commented on .github/workflows/validate-workflow-schema.yml
> +        uses: raven-actions/actionlint@v1
please do not use directly `v1` when action is not official, from github, but commit id (in your other PR you do it, so you have example there)

2025-03-20 09:44 UTC, closed without merging