feat: add command for transferring issue.
asyncapi/.github pull request #314
Opened 2024-09-11 09:37 UTC by Souvikns

**Description**
In this PR I am adding a new workflow file to trasfer issue from one respository to another in AsyncAPI organisation. The command is `/trasfer-issue {repo-name}` or `/ti {repo-name}` for example

```
/trasfer-issue cli
/ti bundler
```

**Related issue(s)**

Resolves #311

2024-09-16 08:39 UTC, derberg reviewed
left some comments, 

you also need to add this new workflow to https://github.com/asyncapi/.github/blob/master/.github/workflows/global-replicator.yml#L141 to have it replicated to all other repos

2024-09-16 08:39 UTC, derberg commented on .github/workflows/transfer-issue.yml
> +        uses: actions/checkout@v2
use latest, which is I think v4, you need to check

2024-09-16 08:39 UTC, derberg commented on .github/workflows/transfer-issue.yml
> +    if: ${{(!github.event.issue.pull_request && github.event.issue.state != 'closed' && github.actor != 'asyncapi-bot') && (contains(github.event.comment.body, '/trasfer-issue') || contains(github.ev
we should probably start using starts with instead of contains

@KhudaDad414 thoughts?

2024-09-16 08:39 UTC, derberg commented on .github/workflows/transfer-issue.yml
> +          sudo apt-get install gh
are you sure it must be installed, afaik runners have it by default. Check other workflows we have, they use `gh` without installation

2024-09-16 08:39 UTC, derberg commented on .github/workflows/transfer-issue.yml
> +          gh action login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
are you sure it is needed? isn't gh preauthenticated already? also we should use GH_TOKEN secret if this is needed explicitly

2024-09-18 13:23 UTC, Souvikns commented on .github/workflows/transfer-issue.yml
> +        uses: actions/checkout@v2
I found this https://github.com/marketplace/actions/setup-the-github-cli

2024-09-18 13:24 UTC, Souvikns commented on .github/workflows/transfer-issue.yml
> +        uses: actions/checkout@v2
I don't think we have any workflow that uses gh cli

2024-09-18 15:05 UTC, derberg commented on .github/workflows/transfer-issue.yml
> +          sudo apt-get install gh
@Souvikns 

example of gh cli usage: https://github.com/asyncapi/spec/blob/master/.github/workflows/update-spec.yaml#L61

some more docs: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-github-cli-in-workflows

basically no login and installation is necessary

2024-09-19 05:56 UTC, Souvikns commented on .github/workflows/transfer-issue.yml
> +          sudo apt-get install gh
Alright, I removed the installation and login, so now I only check parse the comment body and then and use it to trasfer issues.

2024-10-22 07:48 UTC, derberg commented on .github/workflows/transfer-issue.yml
> +    if: ${{(!github.event.issue.pull_request && github.event.issue.state != 'closed' && github.actor != 'asyncapi-bot') && (startsWith(github.event.comment.body, '/trasfer-issue') || startsWith(githu
```suggestion
    if: ${{(!github.event.issue.pull_request && github.event.issue.state != 'closed' && github.actor != 'asyncapi-bot') && (startsWith(github.event.comment.body, '/transfer-issue') || startsWith(github.event.comment.body, '/ti'))}}
```

👁️

2024-10-22 07:52 UTC, derberg commented on .github/workflows/help-command.yml
> +              - \`/trasfer-issue {repo-name}\` or \`/ti {repo-name}\` - trasfers issue from the source repository to the other repository passed by the user. example: \`/ti cli\` or \`/trasfer-issue
`trasfer` all over the place

2024-10-22 07:53 UTC, derberg commented on .github/workflows/help-command.yml
> +              - \`/trasfer-issue {repo-name}\` or \`/ti {repo-name}\` - trasfers issue from the source repository to the other repository passed by the user. example: \`/ti cli\` or \`/trasfer-issue
also aren't we missing a closing ` at the end of the line here?

would be good if you test new workflow and this help workflow in private repo to be 100% sure it all works - before we push it to all the other repos

2024-10-22 07:55 UTC, derberg commented on .github/workflows/transfer-issue.yml
> +      - name: Trasfer Issue
would be very useful to have some interaction with user of the command here, 

if transfer fails (most probably some typo of repo name of misuse of command) we should drop a proper comment in issue that command failed, and they have to make it better - I'm pretty sure we do it for good first issue command

2024-11-11 06:23 UTC, Souvikns commented on .github/workflows/transfer-issue.yml
> +      - name: Trasfer Issue
I have added a step to check if the repo is under the same org and write a comment explaining this to the user.

2024-11-11 06:26 UTC, Souvikns commented on .github/workflows/help-command.yml
> +              - \`/trasfer-issue {repo-name}\` or \`/ti {repo-name}\` - trasfers issue from the source repository to the other repository passed by the user. example: \`/ti cli\` or \`/trasfer-issue
Don't think any ` is missing, it is rendering this 

- `/transfer-issue {repo-name}` or `/ti {repo-name}` - transfer issue from the source repository to the other repository passed by the user. example: `/ti cli` or `/transfer-issue cli`

2024-11-11 10:15 UTC, derberg commented on .github/workflows/help-command.yml
> +              - \`/transfer-issue {repo-name}\` or \`/ti {repo-name}\` - transfer issue from the source repository to the other repository passed by the user. example: \`/ti cli\` or \`/transfer-issu
look at below what is missing in my opinion

<img width="1231" alt="Screenshot 2024-11-11 at 11 14 06" src="https://github.com/user-attachments/assets/4b940ce9-8996-4100-8dd2-575e24a640a5">

2024-11-11 10:18 UTC, derberg commented on .github/workflows/transfer-issue.yml
> +            const issue_number = process.env.ISSUE_NUMBER
please always use `context` if code is executed in `github-script` action, so do not read for example issue number from env variables but like this: `context.issue.number`

2024-11-12 04:20 UTC, Souvikns commented on .github/workflows/transfer-issue.yml
> +          gh issue transfer ${{github.event.issue.number}} asyncapi/${{steps.extract_step.outputs.repo}}
That is basically what I am doing, I am not starting the transfer process unless I can ensure that the repo is correct and under the AsyncAPI organization.

2024-11-12 04:21 UTC, Souvikns commented on .github/workflows/transfer-issue.yml
> +          gh issue transfer ${{github.event.issue.number}} asyncapi/${{steps.extract_step.outputs.repo}}
I think a better error message could be nice. Also, I don't see any way the transfer command failing if the check step is passed.

2024-11-12 09:07 UTC, derberg commented on .github/workflows/transfer-issue.yml
> +          gh issue transfer ${{github.event.issue.number}} asyncapi/${{steps.extract_step.outputs.repo}}
right, you verify if repo exists using api call, that should be enough

2024-11-12 09:08 UTC, derberg commented on .github/workflows/transfer-issue.yml
> +          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```suggestion
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
```

changing to out bot token

2024-11-12 09:10 UTC, derberg commented on .github/workflows/transfer-issue.yml
> +            const repoToMove = process.env.REPO_TO_MOVE
technically where is `REPO_TO_MOVE` and `GITHUB_REPOSITORY` coming from?

2024-12-18 20:04 UTC, derberg commented
@Souvikns ping in case you forgot about this one

2024-12-29 04:43 UTC, Souvikns commented on .github/workflows/transfer-issue.yml
> +            const repoToMove = process.env.REPO_TO_MOVE
`GITHUB_REPOSITORY` is a env variable that is already present in the running it returns you repository name like `asyncapi/cli` format. 

`REPO_TO_MOVE` is something I am extracting in the `Extract Input` step and storing it in the env, and while calling the step `Check Repo` I am passing `REPO_TO_MOVE` as a env on line 55.

2024-12-29 04:49 UTC, Souvikns commented
I have tested the action here: https://github.com/Klifu/API/actions/runs/12532481994. 
You can play around with the functionalities using this repo: https://github.com/Klifu/API, for now only `CLI` repo has issues so you can transfer issues to there.

2025-01-08 16:08 UTC, derberg requested changes

2025-01-08 16:08 UTC, derberg commented on .github/workflows/transfer-issue.yml
> +            const r = process.env.GITHUB_REPOSITORY
I suggest you switch to use standard way of doing things accessing context: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context

`${{ github.repository }}`

2025-01-08 16:08 UTC, derberg commented on .github/workflows/transfer-issue.yml
> +            const repoToMove = process.env.REPO_TO_MOVE
there is no line `55` and also in `Extract Input` there is no such thing as `REPO_TO_MOVE` but `repo`

and anyway you should access it like `steps.extract_step.outputs. repo`

2025-01-28 03:21 UTC, Souvikns commented
@derberg I made the changes, now fetching repo from github context and added missing env for `REPO_TO_MOVE`.

2025-01-29 17:30 UTC, derberg commented
code wise lgtm, did you test it in some repo? just to be 100% sure? as once I merge this one, it will be pushed to all repos.

maybe you can add it first to CLI manually, with the same file name (so it will be later overwritten by this PR))

2025-01-29 17:30 UTC, derberg commented
I'm only referring to `transfer-issue.yml` file

also please add the same header comment as other workflows here have

2025-02-11 13:48 UTC, derberg commented
@Souvikns you need help?

2025-02-26 16:57 UTC, Souvikns commented
> code wise lgtm, did you test it in some repo? just to be 100% sure? as once I merge this one, it will be pushed to all repos.
> 
> maybe you can add it first to CLI manually, with the same file name (so it will be later overwritten by this PR))

I tested in a org that I have, and it is working as expected

2025-02-26 17:02 UTC, Souvikns commented
https://github.com/Klifu/API/actions/runs/13002693693/job/36264188187 I tested in one my org and it is working as expected

2025-02-27 11:07 UTC, derberg approved these changes
lgtm

2025-02-27 11:09 UTC, derberg commented
I'll marge in few hours when most of us sleep as it will trigger CI in all repos, and yeah, we don't want to stress CI/CD setup now

2025-02-27 18:46 UTC, derberg commented
/rtm

2025-02-27 18:46 UTC, merged