ci: add go-pr-testing workflow
asyncapi/.github pull request #42
Opened 2021-03-24 22:51 UTC by smoya

2021-03-26 18:37 UTC, jonaslagoni submitted a review, later dismissed
Looks fined to me, but we might need to start consider another approach in regards to sharing global workflow for multiple languages 🤔 In the end it could be a lot of checks 😅

2021-03-29 12:19 UTC, derberg requested changes
Once you make a small fix I approve as all is good.

2021-03-29 12:19 UTC, derberg commented on .github/workflows/if-go-pr-testing.yml
> +#It does magic only if there is package.json file in the root of the project
go.mod please and not package.json

2021-03-29 14:23 UTC, smoya commented on .github/workflows/if-go-pr-testing.yml
> +#It does magic only if there is package.json file in the root of the project
Fixed!

2021-03-29 15:48 UTC, derberg approved these changes

2021-03-29 18:52 UTC, merged