docs: update how to install global workflows
asyncapi/.github pull request #48
Opened 2021-04-19 10:12 UTC by smoya

This PR updates the instructions for installing global workflows, which can now be installed through GH actions.

2021-04-19 13:29 UTC, jonaslagoni reviewed
Just a small suggestion 👍

2021-04-19 13:29 UTC, jonaslagoni commented on repository-settings.md
> +* Release workflow. [file](https://github.com/asyncapi/.github/blob/master/.github/workflows/if-nodejs-release.ymll)
What if we split the description of the workflow up into something like:
```suggestion
For Node.js projects we have:
* Automated bump of the npm package in its dependent project. [file](https://github.com/asyncapi/.github/blob/master/.github/workflows/if-nodejs-version-bump.yml)
* Release workflow. [file](https://github.com/asyncapi/.github/blob/master/.github/workflows/if-nodejs-release.yml)
```

Since we have different workflows dependent on the language, this seems fitting 🤔

2021-04-19 14:47 UTC, derberg requested changes
@jonaslagoni you also added a new repo recently, you think anything more needs to be updated in this instruction, anything missing?

2021-04-19 14:47 UTC, derberg commented on repository-settings.md
> +### Installation
I don't think we need a section called installation if the previous already has `Add` word. Just keep below text as part of `Add basic GitHub Actions configurations`

2021-04-19 14:47 UTC, derberg commented on repository-settings.md
> +Run **manually** the [Global workflow to rule them all](https://github.com/asyncapi/.github/actions/workflows/global-workflows-support.yml) workflow as shown in the following screenshot:
```suggestion
Add basic workflow by **manually** triggering the [Global workflow to rule them all](https://github.com/asyncapi/.github/actions/workflows/global-workflows-support.yml) workflow as shown in the following screenshot:
```

2021-04-19 15:00 UTC, smoya commented on repository-settings.md
> +* Release workflow. [file](https://github.com/asyncapi/.github/blob/master/.github/workflows/if-nodejs-release.ymll)
I vote for removing that paragraph since it's adding debt since the first moment is just talking about a possible outdated version of this: https://github.com/asyncapi/.github/tree/master/.github/workflows. I think the name on the workflows makes it pretty clear.

2021-04-19 15:01 UTC, smoya commented on repository-settings.md
> +### Installation
done

2021-04-19 16:19 UTC, derberg commented on repository-settings.md
> +* Release workflow. [file](https://github.com/asyncapi/.github/blob/master/.github/workflows/if-nodejs-release.ymll)
tbh, I think we can remove this first part of the section entirely and just replace with simple sentence that there are default workflows for all repositories and link to workflows dir 😄 this list can easily get outdated, links broken, etc

2021-04-19 16:21 UTC, smoya commented on repository-settings.md
> +* Release workflow. [file](https://github.com/asyncapi/.github/blob/master/.github/workflows/if-nodejs-release.ymll)
I think we mean the same here. I removed it.

2021-04-20 06:30 UTC, derberg approved these changes
@smoya side comment from my side - I take back my bashing of `workflow_dispatch` solution. Now I have to say I actually love it because it allows custom input. This means we can have in figure some options in global workflow that when you manually trigger it, you specify the name of the repo that workflow should be triggered against. Cool stuff

2021-04-20 08:03 UTC, merged